##  Estudo de analise financeira de ações

import numpy as np
import pandas as pd 
from pandas_datareader import data as wb
import matplotlib.pyplot as plt

tickers = ['PETR3.SA', 'MGLU3.SA', 'PRIO3.SA', 'ITUB3.SA']
mydata = pd.DataFrame()
for t in tickers:
	mydata[t] = wb.DataReader(t, data_source = 'yahoo', start = '2015-1-1')['Adj Close']

# Normalizando na base 100

(mydata / mydata.iloc[0] * 100).plot(figsize = (15,6))

mydata.plot(figsize=(15,6))
plt.show()

#### CALCULANDO O RETORNO DO PORTIFOLIO

returns = (mydata / mydata.shift(1))

pesos = np.array([0.25,0.25,0.25,0.25])

np.dot(returns, pesos)
annual_returns = returns.mean() * 250
